config/routes.rb
Rails.application.routes.draw do

  root 'application#homepage'

  get '/sessions/new_user/' => 'sessions#new_user', as: :new_user_session
  get '/sessions/new_comedian/' => 'sessions#new_comedian', as: :new_comedian_session
  post '/sessions/create_comedian/' => 'sessions#create_comedian', as: :create_comedian_session
  post '/sessions/create_user/' => 'sessions#create_user', as: :create_user_session
  get '/sessions/logout' => 'sessions#destroy', as: :log_out
  get '/bookings/add_comedian' => 'bookings#create', as: :create_booking
  get '/search_results' => 'application#search_results'
  post '/search_results_input' => 'application#search_results_input'

  resources :users
  resources :sessions
  resources :bookings
  resources :shows do
    resources :reviews
  end
  resources :comedians do
    resources :reviews
  end

  get '/test' => 'application#testing_view'

end

app/models/comedian.rb
class Comedian < ActiveRecord::Base
	has_secure_password
	has_many :bookings
	has_many :reviews
	has_many :shows, :through => :bookings
	has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	validates :name, :username, :password_digest, presence: true
	validates_length_of :bio, maximum: 160


	def show
		@comedian = self
		@show = @comedian.bookings.find_by(show_id: @comedian.id)
	end

	def next_show
		if self.nil?
			""
		else
			self.shows.sort_by(&:date).reverse.first
		end
	end

	def next_show_name
		unless self.next_show.nil?
			self.next_show.show_name
		else
			""
		end
	end

	def average_review
		if self.reviews.blank?
			@average_review = 0
		else
			@average_review = self.reviews.average(:rating).round(2)
		end
	end

end

app/controllers/comedians_controller.rb
class ComediansController < ApplicationController
  before_action :set_comedian, only: [:show, :edit, :update, :destroy]

  # Get a comedian's shows
  # Show.find(Comedian.last.bookings.last.show_id)

  # GET /comedians
  # GET /comedians.json
  def index
    @comedians = Comedian.all
    @bookings = Booking.all
    @shows = Show.all
  end

  # GET /comedians/1
  # GET /comedians/1.json
  def show
    set_comedian
    if @comedian.reviews.blank?
      @average_review = 0
    else
      @average_review = @comedian.reviews.average(:rating).round(2)
    end

    @phone = @comedian.phone.to_i.to_s
    @phone = "3055555555" if @phone.nil?
    @phone = "(#{@phone[0,3]}) #{@phone[3,3]}-#{@phone[6,4]}"

    @twitter_handle = @comedian.twitter_handle
    @twitter_handle = "@wyncode" if @twitter_handle.nil?
    @twitter_url = "http://twitter.com/#{@twitter_handle[1, @twitter_handle.length]}"

    @facebook = @comedian.facebook
    @facebook = "wyncode" if @facebook.nil?
    @facebook_url = "http://www.facebook.com/#{@facebook}"

    @youtube = @comedian.youtube
    @youtube = "wyncode" if @youtube.nil?
    @youtube_url = "http://www.youtube.com/channel/#{@youtube}"

    @instagram = @comedian.instagram
    @instagram = "@wyncode" if @instagram.nil?
    @instagram_url = "http://www.instagram.com/#{@instagram[1, @twitter_handle.length]}"

    @shows = @comedian.shows.sample(2)
    @shows = [] if @shows.nil?
  end

  # GET /comedians/new
  def new
    @comedian = Comedian.new
  end

  # GET /comedians/1/edit
  def edit
  end

  def testing_view
    @comedians = Comedian.all
  end

  # POST /comedians
  # POST /comedians.json
  def create
    @comedian = Comedian.new(comedian_params)
    respond_to do |format|
      if @comedian.save
        format.html { redirect_to @comedian, notice: 'Comedian account was successfully created.' }
        format.json { render :show, status: :created, location: @comedian }
        session[:comedian_id] = @comedian.id
      else
        format.html { render :new }
        format.json { render json: @comedian.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comedians/1
  # PATCH/PUT /comedians/1.json
  def update
    respond_to do |format|
      if @comedian.update(comedian_params)
        format.html { redirect_to @comedian, notice: 'Comedian was successfully updated.' }
        format.json { render :show, status: :ok, location: @comedian }
      else
        format.html { render :edit }
        format.json { render json: @comedian.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comedians/1
  # DELETE /comedians/1.json
  def destroy
    @comedian.destroy
    respond_to do |format|
      format.html { redirect_to comedians_url, notice: 'Comedian was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comedian
      @comedian = Comedian.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comedian_params
      params.require(:comedian).permit(:avatar, :name, :username, :password,
                                       :password_confirmation, :bookings, :bio,
                                       :city, :twitter_handle, :facebook, :youtube,
                                       :phone, :email, :instagram)
    end
end

app/helpers/comedians_helper.rb
module ComediansHelper
end

app/views/comedians/_comedians_panel.html.erb
<section id='#comedians'>
  <div class="group-panel">
    <div class="container-fluid">
      <div class="container group-show-panel-heading text-center">
        <br>
        <h1 class="gallery">Top Rated Comedians</h1>
        <br>
      </div>
      <div class="row">
        <% counter = 1 %>
        <% @comedians.each do |x| %>
          <% if (counter + 3) % 4 == 0 %>
            <div class="horiz-flex-box space-around">
          <% end %>
        <!-- Real box beginning -->
              <div class="col-xs-4 col-lg-2 comedian-panel-container-outer
                          comedian-hover-box">
                <!-- <div class="panel-body comedian-filler-box" style="display:none;"></div> -->
                <div class="panel-body comedian-panel-container-body">
                  <div class="vert-flex-box">
                    <div class="horiz-flex-box">
                      <div class="vert-flex-box col-lg-12">
                        <div class="comedian-panel-body-line">
                          <h3><%= link_to x.name, x, class: "comedian-table-link" %></h3>
                        </div>
                        <%= link_to image_tag(x.avatar.url(:medium),
                              class: "img-rounded img-responsive img-left panel-image"), x %>
                        <div class="comedian-panel-body-line">
                          <h4>
                            <div class="average-review-rating" data-score=<%= x.average_review %>>
                              <span>
                                <p class="profile-rating"><%= x.reviews.count %> reviews</p>
                              </span>
                            </div>
                          </h4>
                        </div>
                      </div>
                    <div class="vert-flex-box col-lg-12 hidden">
                      <h4>Upcoming Shows</h4>
                        <% x.shows.each do |show| %>
                      <div>
                        <% unless x.show.nil? || x.next_show.date.nil? %>
                          <%= link_to show.show_name, show_path(show), class: "comedian-table-link" %>
                        <% end %>
                      </div>
                      <% end %>
                      <div class="comedian-panel-body-line hidden">
                        <h4>Bio: </h4>
                        <div class="vert-flex-box comedian-panel-bio"><%= x.bio %></div>
                      </div>
                    </div>
                  </div>
                <div class="horiz-flex-box space-around hidden comedian-panel-bottom">
                  <div>
                    <i class="fa fa-twitter" style="font-size:36px" aria-hidden="true"></i>
                    <%= x.twitter_handle %>
                  </div>
                  <div>
                    <i class="fa fa-facebook-official" style="font-size:36px" aria-hidden="true"></i>
                    <%= x.facebook %>
                  </div>
                  <div>
                    <i class="fa fa-youtube" style="font-size:36px" aria-hidden="true"></i>
                    <%= x.youtube %>
                  </div>
                </div>
              </div>
            </div>
          </div>
            <% if counter % 4 == 0 %>
        </div>
            <% end %>
            <% counter += 1 %>
              <!-- Real box end -->
          <% end %>
      </div>
    </div>
  </div>
</section>

app/views/comedians/_comedians_reviews.html.erb
<% unless @comedian.nil? %>
	<% unless @comedian.reviews.nil? %>
		<% @comedian.reviews.each do |r| %>
			<div class="individual-comedian-comment">
				<div class="col-lg-3 comedian-comment-left vert-flex-box">
					<div class="review-rating" data-score="<%= r.rating %>">
					</div>
				</div>
				<div class="col-lg-9">
					<p class="comment-body"><%= r.comment %></p>
				</div>
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/comedians/_form.html.erb
<%= form_for @comedian, html: { multipart: true } do |f| %>
  <% if @comedian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comedian.errors.count, "error") %> prohibited this comedian from being saved:</h2>

      <ul>
      <% @comedian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="comedian-signup-container">
    <div>
      <div class="col-md-6">
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :name %></span>
          <%= f.text_field :name, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
        <br>
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :username %></span>
          <%= f.text_field :username, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
        <br>
        <div class="field">
          <%= f.label :avatar %><br>
          <%= f.file_field :avatar %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :password %></span>
          <%= f.password_field :password, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
        <br>
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :password_confirmation %></span>
          <%= f.password_field :password_confirmation, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
      </div>
    </div>
    <br>
    <div class="actions submit-and-back-buttons-container">
      <div>
        <%= f.submit :Update_Account %>
      </div>
      <div>
        <%= button_to 'Back', root_path %>
      </div>
    </div>
  </div>
<% end %>

app/views/comedians/_profile.html.erb
<%= form_for @comedian, html: { multipart: true } do |f| %>
  <% if @comedian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comedian.errors.count, "error") %> prohibited this comedian from being saved:</h2>

      <ul>
      <% @comedian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="comedian-signup-container">
    <div>
      <div class="col-md-6">
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :bio %></span>
          <%= f.text_area :bio, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
      </div>
        <br>
      <div class="col-md-6">
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :city %></span>
          <%= f.text_field :city, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
      </div>
        <br>
      <div class="col-md-6">
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :twitter_handle %></span>
          <%= f.text_field :twitter_handle, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
      </div>
        <br>
      <div class="col-md-6">
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :facebook %></span>
          <%= f.text_field :facebook, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
      </div>
        <br>
      <div class="col-md-6">
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :youtube %></span>
          <%= f.text_field :youtube, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :instagram %></span>
          <%= f.text_field :instagram, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :email %></span>
          <%= f.text_field :email, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="input-group">
          <span class="input-group-addon", id="basic-addon1"><%= f.label :phone %></span>
          <%= f.text_field :phone, class: "form-control", 'aria-describedby':"basic-addon1" %>
        </div>
      </div>

    </div>
    <br>
    <div class="actions submit-and-back-buttons-container">
      <div>
        <%= f.submit :Update_Profile %>
      </div>
      <div>
        <%= button_to 'Back', comedian_path(@comedian) %>
      </div>
    </div>
  </div>
<% end %>

app/views/comedians/edit.html.erb
<div class="jumbotron text-center">
	<h1>Edit Account Profile</h1>
</div>

<div class="container-fluid">
	<h3>Account Info</h3>
<%= render 'form' %>
</div>
<div class="container-fluid">
	<h3>Profile Info</h3>
<%= render 'profile' %>
</div>

<%= link_to 'Show', @comedian %> |
<%= link_to 'Back', comedians_path %>

app/views/comedians/index.html.erb
<%= render 'comedians/comedians_panel' %>

app/views/comedians/new.html.erb
<div id="comediansignup">
  <div class="col-md-6 col-centered comedian-signup-master-container">
    <h1> Comedian Sign Up </h1>
    <br><br>
    <%= render 'form' %>
  </div>
</div>

app/views/comedians/show.html.erb
<p id="notice"><%= flash[:notice_login] %></p>

<link href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css" rel="stylesheet" media="screen">
<div class="container">
  <div class="row user-menu-container square">
    <div class="col-md-7 user-details">
      <div class="row coralbg white">
        <div class="col-md-6 no-pad">
          <%= image_tag @comedian.avatar.url(:medium), height: "220", width: "220" %>
        </div>
        <div class="col-md-6 no-pad">
          <div class="user-pad vert-flex-box center">
            <div class="horiz-flex-box flex-start">
              <h3 class="com-prof-name"><%= @comedian.name %></h3>
            </div>
            <div class="horiz-flex-box flex-start">
              <h4 class="white">
                <i class="fa fa-check-circle-o"></i>
                <%= @comedian.city %>
              </h4>
            </div>
            <div class="horiz-flex-box flex-start">
              <h4 class="white">
                <i class="fa fa-twitter"></i> <%= @comedian.twitter_handle %>
              </h4>
            </div>
            <% if current_comedian == @comedian %>
            <a href="<%= edit_comedian_path(@comedian) %>">
              <button type="button" class="btn btn-labeled btn-danger">
                <span class="btn-label">
                  <i class="fa fa-pencil"></i>
                </span>Edit Profile
              </button>
            </a>
              <% end %>
          </div>
        </div>
      </div>
      <div class="row overview">
        <div class="col-md-4 user-pad text-center">
          <h3>FOLLOWERS</h3>
          <h4>2,784</h4>
        </div>
        <div class="col-md-4 user-pad text-center">
          <h3>FOLLOWING</h3>
          <h4>456</h4>
        </div>
        <div class="col-md-4 user-pad text-center">
          <h3>RATING</h3>
          <div class="average-review-rating show-show horiz-flex-box center"
               data-score=<%= @average_review %>>
          </div>
          <span>
            <p class="profile-rating">Based on <%= @comedian.reviews.count %> reviews</p>
          </span>
        </div>
      </div>
    </div>
    <div class="col-md-1 user-menu-btns vert-button-container">
      <div class="btn-group-vertical square vert-button-container" id="responsive">
        <a href="#" class="btn btn-block btn-inverse com-prof-button active">
          <i class="fa fa-bell-o fa-3x"></i>
        </a>
        <a href="#" class="btn btn-inverse com-prof-button">
          <i class="fa fa-envelope-o fa-3x"></i>
        </a>
        <a href="#" class="btn btn-inverse com-prof-button">
          <i class="fa fa-laptop fa-3x"></i>
        </a>
        <a href="#" class="btn btn-inverse com-prof-button">
          <i class="fa fa-cloud-upload fa-3x"></i>
        </a>
      </div>
    </div>
    <div class="col-md-4 user-menu user-pad">
      <div class="user-menu-content active">
        <h3>
          Upcoming Shows
        </h3>
        <div class="vert-flex-box col-lg-8 space-around comedian-upcoming-shows">
          <% @shows.each do |show| %>
            <div class="horiz-flex-box flex-start">
              <div class="sm-icon vert-flex-box center">
                <i class="fa fa-hand-o-right"></i>
              </div>
              <span class="sm-text">
                <h3><%= link_to show.show_name, show %></h3>
                <ul>
                  <li><%= link_to show.venue, show %></li>
                  <li><%= link_to show.date, show %></li>
                </ul>
              </span>
            </div>
          <% end %>
        </div>
      </div>
      <div class="user-menu-content">
        <a class="twitter-timeline" href="https://twitter.com/<%= @twitter_handle[1,@twitter_handle.length] %>" height="350px" data-widget-id="724738053403713536" data-screen-name="<%= @twitter_handle[1, @twitter_handle.length] %>">Tweets by <%= @twitter_handle %></a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>
      <div class="user-menu-content">
        <iframe src="http://www.youtube.com/embed/?listType=user_uploads&list=<%= @youtube %>" width="350" height="350"></iframe>
      </div>
      <div class="user-menu-content">
        <h2 class="text-center">
          Contact Info <br>
          & <br>
          Social Media
        </h2>
        <div class="share-links col-lg-8 col-centered">
          <div class="vert-flex-box center">
              <div class="horiz-flex-box flex-start">
                <span class="sm-text">
                  <%= @comedian.name %>
                </span>
              </div>
              <div class="horiz-flex-box flex-start">
                <span class="sm-icon">
                  <i class="fa fa-phone" aria-hidden="true"></i>
                </span>
                <span class="sm-text">
                  <%= @phone %>
                </span>
              </div>
              <div class="horiz-flex-box flex-start">
                <span class="sm-icon">
                  <i class="fa fa-envelope" aria-hidden="true"></i>
                </span>
                <span class="sm-text">
                  <%= @comedian.email %>
                </span>
              </div>
              <div class="horiz-flex-box flex-start">
                <span class="sm-icon">
                  <i class="fa fa-twitter" aria-hidden="true"></i>
                </span>
                <span class="sm-text">
                  <%= link_to @twitter_handle, @twitter_url %>
                </span>
              </div>
              <div class="horiz-flex-box flex-start">
                <span class="sm-icon">
                  <i class="fa fa-facebook-square" aria-hidden="true"></i>
                </span>
                <span class="sm-text">
                  <%= link_to @facebook, @facebook_url %>
                </span>
              </div>
              <div class="horiz-flex-box flex-start">
                <span class="sm-icon">
                  <i class="fa fa-youtube-square" aria-hidden="true"></i>
                </span>
                <span class="sm-text">
                  <%= link_to @youtube, @youtube_url %>
                </span>
              </div>
              <div class="horiz-flex-box flex-start">
                <span class="sm-icon">
                  <i class="fa fa-instagram" aria-hidden="true"></i>
                </span>
                <span class="sm-text">
                  <%= link_to @instagram, @instagram_url %>
                </span>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Reviews Code -->
<div class="reviews container">
  <div class="background-comedian-review-master vert-flex-box flex-start">
    <% if current_user %>
      <%= render "reviews/comedian_form"%>
    <% end %>
    <div class="col-md-10 col-centered vert-flex-box comment-container">
      <p id="notice"><%= flash[:notice_signin] %></p>
        <%= render 'comedians_reviews' %>
    </div>
  </div>
</div>