config/routes.rb
Rails.application.routes.draw do

  root 'application#homepage'

  get '/sessions/new_user/' => 'sessions#new_user', as: :new_user_session
  get '/sessions/new_comedian/' => 'sessions#new_comedian', as: :new_comedian_session
  post '/sessions/create_comedian/' => 'sessions#create_comedian', as: :create_comedian_session
  post '/sessions/create_user/' => 'sessions#create_user', as: :create_user_session
  get '/sessions/logout' => 'sessions#destroy', as: :log_out
  get '/bookings/add_comedian' => 'bookings#create', as: :create_booking
  get '/search_results' => 'application#search_results'
  post '/search_results_input' => 'application#search_results_input'

  resources :users
  resources :sessions
  resources :bookings
  resources :shows do
    resources :reviews
  end
  resources :comedians do
    resources :reviews
  end

  get '/test' => 'application#testing_view'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery

  helper_method :current_user, :current_comedian

  def current_user
  	@current_user ||= User.find_by(id: session[:user_id])
  end

  def current_comedian
  	@current_comedian ||= Comedian.find_by(id: session[:comedian_id])
  end

  def require_logged_in
  	return true if current_user || current_comedian

  	return redirect_to root_path
  end

  def require_comedian_logged_in
  	return true if current_comedian

  	return redirect_to root_path
  end

  def testing_view
    @comedian = Comedian.first
  end

  def search_logic(search_array = params)
    @comedians = nil
    @comedian = Comedian.new
    @show = Show.new
    @shows = nil
    @bookings = Booking.all
    @booking = Booking.new
    @user = User.new
    @users = User.all
    @return_type = nil


    if params[:username]
      @comedians = Comedian.where(username: params[:username])
      @return_type = "com"
    end
    if params[:name]
      @comedians = Comedian.where(name: params[:name])
      @return_type = "com"
    end
    if params[:venue]
      @shows = Show.where(venue: params[:venue])
      @return_type = "show"
    end
    if params[:show_name]
      @shows = Show.where(show_name: params[:show_name])
      @return_type = "show"
    end
    if params[:date]
      @shows = Show.where(date: params[:date])
      @return_type = "show"
    end
    if params[:time]
      @shows = Show.where(time: params[:time])
      @return_type = "show"
    end
  end

  def search_results_input
    p params
    search_inputs = params
    p "^" * 50
    p search_inputs
    p "^" * 50
    search_inputs.each do |k, v|
      search_inputs[k] = nil if v == ""
    end
    search_logic(search_inputs)
    @return = [@return_type, @shows, @comedians]
    p "*" * 50
    p "post request input"
    p @return
    p "*" * 50
    p search_inputs
    p "*" * 50

    respond_to do |format|
      format.js
    end
  end

  def search_results
  end

  def homepage
    search_logic
    @comedians = Comedian.all
    @shows = Show.all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form.html.erb
<%= form_for(@booking) do |f| %>
  <%= f.text_field :username %>
  <%= f.submit %>
<% end %>

app/views/application/_index.html.erb
<!-- Search form for comedians and their shows -->
<div class="comedian-signup-master-container col-md-8 col-centered">
  <h1>Search Comedian Shows</h1>
  <br><br>
  <div class="comedian-signup-container">
    <div>
      <!-- first form col -->
      <div class="col-md-6">
        <!-- first form -->
        <%= form_tag '', :method => :get, :remote => true  do %>
          <div class="horiz-flex-box">
            <div class="input-group col-md-9">
              <span class="input-group-addon", id="basic-addon1">
                <%= label_tag :name, "Comedian name" %>
              </span>
            <%= text_field_tag :name, nil, class: "form-control", 'aria-describedby':"basic-addon1" %>
            </div>
          <%= submit_tag 'Filter', class:"search-filter-button" %>
          <% end %>
        </div>
        <!-- end first form -->
        <br>
        <!-- second form -->
        <%= form_tag '', :method => :get do %>
          <div class="horiz-flex-box">
            <div class="input-group col-md-9">
              <span class="input-group-addon", id="basic-addon1">
                <%= label_tag :venue, "Venue" %>
              </span>
            <%= text_field_tag :venue, nil, class: "form-control", 'aria-describedby':"basic-addon1" %>
            </div>
          <%= submit_tag 'Filter' %>
          <% end %>
        </div>
        <!-- end second form -->
        <br>
        <!-- third form -->
        <%= form_tag '', :method => :get do %>
          <div class="horiz-flex-box">
            <div class="input-group col-md-9">
              <span class="input-group-addon", id="basic-addon1">
                <%= label_tag :show_name, "Show Name" %>
              </span>
            <%= text_field_tag :show_name, nil, class: "form-control", 'aria-describedby':"basic-addon1" %>
            </div>
          <%= submit_tag 'Filter' %>
          <% end %>
        </div>
        <!-- end third form -->
        <br>
      </div>
      <!-- end first form col -->
      <!-- begin second form col -->
      <div class="col-md-6">
        <!-- begin fourth form -->
        <%= form_tag '', :method => :get do %>
          <div class="horiz-flex-box">
            <div class="input-group col-md-9">
              <span class="input-group-addon", id="basic-addon1">
                <%= label_tag :date, "Search by date" %>
              </span>
            <%= date_field_tag :date, nil, class: "form-control", 'aria-describedby':"basic-addon1" %>
          </div>
          <%= submit_tag 'Filter' %>
          <% end %>
        </div>
        <!-- end fourth form -->
        <br>
        <!-- begin fifth form -->
        <%= form_tag '', :method => :get, remote:true do %>
          <div class="horiz-flex-box">
            <div class="input-group col-md-9">
              <span class="input-group-addon", id="basic-addon1">
                <%= label_tag :time, "Search by time" %>
              </span>
              <%= time_field_tag :time, nil, class: "form-control", 'aria-describedby':"basic-addon1" %>
            </div>
          <%= submit_tag 'Filter' %>
          <% end %>
        </div>
        <!-- end fifth form -->
        <br>
      </div>
      <!-- end second form col -->
    </div>
  </div>
  <%= button_to "Start Over", root_path %>
</div>
<!-- Comedian Table starts here -->
<div class="container col-centered table-responsive" id="comedians-list-table-container">
  <table id="table-show" class="table table-hover">
    <col class="comedian-1">
    <col class="comedian-2">
    <tr class="custom">
      <h2>Search Results</h2>
    </tr>
    <thead>
    <tr class="warning">
      <th>Comedian</th>
      <th>Upcoming Show</th>
    </tr>
    </thead>
    <% @bookings.each do |b| %>
      <tbody>
        <tr>
          <td>
            <ul class="list-unstyled">
              <%= link_to(b.comedian) do %>
                <li class="centered-list-item"><%= image_tag b.comedian.avatar.url(:thumb)%></li>
                <li class="centered-list-item"><%= b.comedian.name %></li>
              <% end %>
            </ul>
          </td>
          <td>
            <ul class="list-unstyled">
              <%= link_to(b.show) do %>
                <li>Event Name:<%= b.show.show_name %></li>
                <li>Show Venue:<%= b.show.venue %></li>
                <li>Show Date:<%= b.show.date %></li>
                <li>Show Time:<%= b.show.time %></li>
              <% end %>
            </ul>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/application/_navbar_logged_in.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="icon-background">
      <a class="navbar-brand" href="/">
        <%= image_tag("OpenMiic/open_mike-02.png", size: "50x50", id: "navbar-logo") %>
        <!-- <i class="fa fa-microphone" aria-hidden="true"></i> -->
      </a>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if current_page?('/') %>
          <li><a class="page-scroll" href="#services">Purpose</a></li>
        <% end %>
        <li><a class="page-scroll" href="/comedians">Comedians</a></li>
        <li><a href="/shows">Shows</a></li>
        <li><a href="/shows/new">Create A Show</a></li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <p class="nav navbar-nav navbar-text alert-success"><%= flash[:notice_login] %></p>
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user.nil? %>
        <li><%= content_tag(:a, "My Profile", href: "/users/#{current_user.id}") %></li>
        <% elsif !current_comedian.nil? %>
        <li><%= content_tag(:a, "My Profile", href: "/comedians/#{current_comedian.id}") %></li>
        <% end %>
        <li><%= link_to 'Log Out', log_out_path, action: :destroy %></li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_navbar_logged_out.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag("OpenMiic/open_mike-02.png", size: "50x50", id: "navbar-logo") %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <% if current_page?('/') %>
            <li><a class="page-scroll" href="#services">Purpose</a></li>
          <% end %>
        <li><a href="/comedians">Comedians</a></li>
        <li><a href="/shows">Shows</a></li>
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> -->
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Log In<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/sessions/new_comedian">Log In as Comedian</a></li>
            <li><a href="/sessions/new_user">Log In as User</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sign Up!<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/comedians/new">Sign up as Comedian</a></li>
            <li><a href="/users/new">Sign up as User</a></li>
          </ul>
        </li>
      </ul>
          <!-- in nav navbar-nav right, <li class="active">
        <a class="page-scroll" href="#services">Purpose</a></li>
        -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_partial_render_logic.html.erb
<% if @return_type == 'show' %>
  <%= render 'shows/shows_panel' %>
<% else %>
  <%= render 'comedians/comedians_panel' %>
<% end %>

app/views/application/homepage.html.erb
    <!-- Image Background Page Header -->
    <!-- Note: The background image is set within the business-casual.css file. -->
    <header class="business-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                </div>
            </div>
        </div>
    </header>

<!-- Comedian panels -->

<%= render 'bookings/index' %>
<div class='render-search-results' >
  <%= render 'application/partial_render_logic' %>
</div>


    <!-- Page Content -->
    <section id="services" class="landing-background">
      <div class="jumbotron text-center">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h1 class="section-heading">Connecting the community through laughter</h1>
            <hr class="jumbo">
            <h2>Find top rated comedians in your area</h2>
            <br><br><br><br>
          </div>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-lg-3 col-md-4 text-center">
              <div class="service-box">
                <div class="bounce-on-hover">
                  <a href="/comedians"><i class="fa fa-comments" style="font-size:48px;color:#ac1c35; animation-name: bounceIn"></i></a>
                </div>
                <h2 class="jumbo">Local Comedians</h2>
                <p class="text-muted">Checkout comedian profiles to see when they are performing and what the locals say about them.</p>
              </div>
            </div>
            <div class="col-lg-3 col-md-4 text-center">
              <div class="service-box">
                <div class="bounce-on-hover">
                  <a href="/shows"><i class="fa fa-sitemap" style="font-size:48px;color:#ac1c35; animation-name: bounceIn"></i></a>
                </div>
                <h2 class="jumbo">A Social Network</h2>
                 <p class="text-muted">Stay current with discussion in the comedic industry.</p>
              </div>
            </div>
            <div class="col-lg-3 col-md-4 text-center">
              <div class="service-box">
                <div class="bounce-on-hover">
                  <i class="fa fa-user-plus animated bounceIn" style="font-size:48px;color:#ac1c35; animation-name: bounceIn"></i>
                </div>
                <h2 class="jumbo">Search and Book Local Shows</h2>
                <p class="text-muted">Finally find a quick and easy way to find all the best shows closest to you.</p>
              </div>
            </div>
            <div class="col-lg-3 col-md-4 text-center">
              <div class="service-box">
                <div class="bounce-on-hover">
                  <i class="fa fa-line-chart animated bounceIn" style="font-size:48px;color:#ac1c35; animation-name: bounceIn"></i>
                </div>
                <h2 class="jumbo">Watch Talent Flourish</h2>
                <p class="text-muted">A platform to showcase aspiring comedians and build reputation. </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

app/views/application/search_results_input.js.erb
$('.render-search-results')
  .empty()
  .append("<%=j render 'application/partial_render_logic', locals: {comedians: @comedians} %>");

app/views/application/testing_view.html.erb
<link href="http://fontawesome.io/assets/font-awesome/css/font-awesome.css" rel="stylesheet" media="screen">
<div class="container">
    <div class="row user-menu-container square">
        <div class="col-md-7 user-details">
            <div class="row coralbg white">
                <div class="col-md-6 no-pad">
                    <div class="user-pad">
                        <h3>Welcome back, <%= @comedian.name %></h3>
                        <h4 class="white"><i class="fa fa-check-circle-o"></i> San Antonio, TX</h4>
                        <h4 class="white"><i class="fa fa-twitter"></i> CoolesOCool</h4>
                       	<a href="<%= edit_comedian_path(@comedian) %>"><button type="button" class="btn btn-labeled btn-danger">
                            <span class="btn-label"><i class="fa fa-pencil"></i></span>Update</button></a>
                    </div>
                </div>
                <div class="col-md-6 no-pad">
                    <div class="user-image">
                        <%= image_tag @comedian.avatar.url(:medium) %>
                    </div>
                </div>
            </div>
            <div class="row overview">
                <div class="col-md-4 user-pad text-center">
                    <h3>FOLLOWERS</h3>
                    <h4>2,784</h4>
                </div>
                <div class="col-md-4 user-pad text-center">
                    <h3>FOLLOWING</h3>
                    <h4>456</h4>
                </div>
                <div class="col-md-4 user-pad text-center">
                    <h3>APPRECIATIONS</h3>
                    <h4>4,901</h4>
                </div>
            </div>
        </div>
        <div class="col-md-1 user-menu-btns vert-button-container">
          <div class="btn-group-vertical square vert-button-container" id="responsive">
            <a href="#" class="btn btn-block btn-default com-prof-button active">
              <i class="fa fa-bell-o fa-3x"></i>
            </a>
            <a href="#" class="btn btn-default com-prof-button">
              <i class="fa fa-envelope-o fa-3x"></i>
            </a>
            <a href="#" class="btn btn-default com-prof-button">
              <i class="fa fa-laptop fa-3x"></i>
            </a>
            <a href="#" class="btn btn-default com-prof-button">
              <i class="fa fa-cloud-upload fa-3x"></i>
            </a>
          </div>
        </div>
        <div class="col-md-4 user-menu user-pad">
            <div class="user-menu-content active">
                <h3>
                    Recent Interactions
                </h3>
                <ul class="user-menu-list">
                    <li>
                        <h4><i class="fa fa-user coral"></i> Roselynn Smith followed you.</h4>
                    </li>
                    <li>
                        <h4><i class="fa fa-heart-o coral"></i> Jonathan Hawkins followed you.</h4>
                    </li>
                    <li>
                        <h4><i class="fa fa-paper-plane-o coral"></i> Gracie Jenkins followed you.</h4>
                    </li>
                    <li>
                        <button type="button" class="btn btn-labeled btn-warning" href="#">
                            <span class="btn-label"><i class="fa fa-bell-o"></i></span>View all activity</button>
                    </li>
                </ul>
            </div>
            <div class="user-menu-content">
                <h3>
                    Your Inbox
                </h3>
                <ul class="user-menu-list">
                    <li>
                        <h4>From Roselyn Smith <small class="coral"><strong>NEW</strong> <i class="fa fa-clock-o"></i> 7:42 A.M.</small></h4>
                    </li>
                    <li>
                        <h4>From Jonathan Hawkins <small class="coral"><i class="fa fa-clock-o"></i> 10:42 A.M.</small></h4>
                    </li>
                    <li>
                        <h4>From Georgia Jennings <small class="coral"><i class="fa fa-clock-o"></i> 10:42 A.M.</small></h4>
                    </li>
                    <li>
                        <button type="button" class="btn btn-labeled btn-danger" href="#">
                            <span class="btn-label"><i class="fa fa-envelope-o"></i></span>View All Messages</button>
                    </li>
                </ul>
            </div>
            <div class="user-menu-content">
                <h3>
                    Trending
                </h3>
                <div class="row">
                    <div class="col-md-6">
                        <div class="view">
                            <div class="caption">
                                <p>47LabsDesign</p>
                                <a href="" rel="tooltip" title="Appreciate"><span class="fa fa-heart-o fa-2x"></span></a>
                                <a href="" rel="tooltip" title="View"><span class="fa fa-search fa-2x"></span></a>
                            </div>
                            <img src="https://placehold.it/350x150" class="img-responsive">
                        </div>
                        <div class="info">
                            <p class="small" style="text-overflow: ellipsis">An Awesome Title</p>
                            <p class="small coral text-right"><i class="fa fa-clock-o"></i> Posted Today | 10:42 A.M.</small>
                        </div>
                        <div class="stats turqbg">
                            <span class="fa fa-heart-o"> <strong>47</strong></span>
                            <span class="fa fa-eye pull-right"> <strong>137</strong></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="view">
                            <div class="caption">
                                <p>47LabsDesign</p>
                                <a href="" rel="tooltip" title="Appreciate"><span class="fa fa-heart-o fa-2x"></span></a>
                                <a href="" rel="tooltip" title="View"><span class="fa fa-search fa-2x"></span></a>
                            </div>
                            <img src="https://placehold.it/350x150" class="img-responsive">
                        </div>
                        <div class="info">
                            <p class="small" style="text-overflow: ellipsis">An Awesome Title</p>
                            <p class="small coral text-right"><i class="fa fa-clock-o"></i> Posted Today | 10:42 A.M.</small>
                        </div>
                        <div class="stats turqbg">
                            <span class="fa fa-heart-o"> <strong>47</strong></span>
                            <span class="fa fa-eye pull-right"> <strong>137</strong></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="user-menu-content">
                <h2 class="text-center">
                    START SHARING
                </h2>
                <center><i class="fa fa-cloud-upload fa-4x"></i></center>
                <div class="share-links">
                    <center><button type="button" class="btn btn-lg btn-labeled btn-success" href="#" style="margin-bottom: 15px;">
                            <span class="btn-label"><i class="fa fa-bell-o"></i></span>A FINISHED PROJECT
                    </button></center>
                    <center><button type="button" class="btn btn-lg btn-labeled btn-warning" href="#">
                            <span class="btn-label"><i class="fa fa-bell-o"></i></span>A WORK IN PROGRESS
                    </button></center>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- <p id="notice">
<%#notice %>

</p>
<%#image_tag @comedian.avatar.url(:thumb)%>
<p>
  <strong>Name:</strong>
  <%#@comedian.name %>
</p>

<p>
  <strong>Username:</strong>
  <%#@comedian.username %>
</p>

<p>
  <strong>Upcoming Shows:</strong>
  <%#@comedian.shows.each do |x| %>
    <%#link_to x.show_name, x %>
  <%# #end %>
</p>

<%# #link_to 'Edit', edit_comedian_path(@comedian) %> |
<%# #link_to 'Back', root_path %> -->
<div class="container">
  <div class="col-md-1">
    <p id="notice"><%= flash[:notice_signin] %></p>
    <%= render @comedian.reviews %>
    <div>
      <%= link_to "Add Review", new_comedian_review_path(@comedian) %>
    </div>
  </div>
</div>
<script src="jquery.raty.js"></script>
<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>


<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>