config/routes.rb
Rails.application.routes.draw do

  root 'application#homepage'

  get '/sessions/new_user/' => 'sessions#new_user', as: :new_user_session
  get '/sessions/new_comedian/' => 'sessions#new_comedian', as: :new_comedian_session
  post '/sessions/create_comedian/' => 'sessions#create_comedian', as: :create_comedian_session
  post '/sessions/create_user/' => 'sessions#create_user', as: :create_user_session
  get '/sessions/logout' => 'sessions#destroy', as: :log_out
  get '/bookings/add_comedian' => 'bookings#create', as: :create_booking
  get '/search_results' => 'application#search_results'
  post '/search_results_input' => 'application#search_results_input'

  resources :users
  resources :sessions
  resources :bookings
  resources :shows do
    resources :reviews
  end
  resources :comedians do
    resources :reviews
  end

  get '/test' => 'application#testing_view'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_comedian
  before_action :check_current_user, only: [:create, :edit, :destroy]
  before_action :find_review, only: [:show, :edit, :update, :destroy]

	def new
		@review = Review.new
	end

	def create
    @review = Review.new(review_params)
    if @comedian.nil?
      @review.show_id = @show.id
    elsif @show.nil?
      #associate book with current user
      @review.comedian_id = @comedian.id
    end

    @review.user_id = current_user.id

		if @review.save
      if @review.comedian_id
        @review_direction = "com"
			 redirect_to comedian_path(@comedian)
      elsif @review.show_id
        @review_direction = "show"
        redirect_to show_path(@show)
      end
		else
			render 'new'
		end
	end

  def show
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to comedian_path(@comedian)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to comedian_path
  end

	private

	def review_params
		p "*" * 50
		p params
		p "*" * 50
		params.require(:review).permit(:rating, :comment, :id)
	end

	def find_comedian
      if (params[:comedian_id]).nil?
        @show = Show.find(params[:show_id])
      elsif
        @comedian = Comedian.find(params[:comedian_id])
      end
	end

  def check_current_user
    if current_user.nil?
      flash[:notice_signin] = "Please log in to contribute."
      return redirect_to comedian_path(@comedian)
    end
  end

  def find_review
    @review = Review.find(params[:id])
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_comedian_form.html.erb
<br>
<div class="comedian-review-master-container col-md-8 col-centered">
	<h2>Write a Review!</h2>
	<div class="comedian-review-container comedian-form center">
		<div class="rating-form-box horiz-flex-box">
			<%= form_for([@comedian, @comedian.reviews.build]) do |f| %>
			<div id="rating-form" class="rating-form">
			</div>
		</div>
		<div class="">
			<div class="">
				<%= f.text_area :comment, class:'textarea comedian' %>
			</div>
		</div>
		<div class="">
			<%= f.submit %>
		</div>
		<% end %>
	</div>
</div>

app/views/reviews/_form.html.erb
<div class="background-comedian-signup-master">
<br>
	<div class="comedian-signup-master-container col-md-8 col-centered">
	<br>
		<div class="comedian-signup-container">
			<div class="col-md-12 row">
			<%= form_for([@comedian, @comedian.reviews.build]) do |f| %>
				<div class="horiz-flex-box field col-lg-1">
					<span class="input-group-addon", id="basic-addon1">
						<div id="rating-form">
				<%= f.label :rating %><br>
						</div>
					</span>
				</div>
			</div>
			<br><br><br>
			<div class="col-md-12 row">
				<div class="horiz-flex-box field col-lg-2">
					<span class="input-group-addon", id="basic-addon1">
				<%= f.label :comment %><br>
					</span>
				</div>
				<br><br>
				<div class="container-fluid">
				<%= f.text_area :comment, class:'textarea' %>
				</div>
			</div>
			<div class="actions">
				<%= f.submit %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/reviews/_review.html.erb
<% @comedian.reviews.each do |r| %>
	<div>
		<div class="review-rating" data-score="<%= r.rating %>">
		</div>
		<p class="review-comment"><%= r.comment %></p>
		<% if current_user %>
			<% if r.user_id == current_user.id %>
				<%= link_to "Edit", edit_comedian_review_path(r.comedian, r), class: "btn btn-warning" %>
				<%= link_to "Delete", comedian_review_path(r.comedian, r), method: :delete, date: {confirm: "Are you sure?" }, class: "btn btn-warning" %>
	</div>
			<% end %>
		<% end %>
	<% end %> 	

app/views/reviews/_show_form.html.erb
<div class="background-comedian-signup-master">
<br>
	<div class="comedian-signup-master-container col-md-8 col-centered">
	<br>
		<div class="comedian-signup-container">
			<div class="col-md-12 row">
			<%= form_for([@comedian, @comedian.reviews.build]) do |f| %>
				<div class="horiz-flex-box field col-lg-1">
					<span class="input-group-addon", id="basic-addon1">
						<div id="rating-form">
				<%= f.label :rating %><br>
						</div>
					</span>
				</div>
			</div>
			<br><br><br>
			<div class="col-md-12 row">
				<div class="horiz-flex-box field col-lg-2">
					<span class="input-group-addon", id="basic-addon1">
				<%= f.label :comment %><br>
					</span>
				</div>
				<br><br>
				<div class="container-fluid">
				<%= f.text_area :comment, class:'textarea' %>
				</div>
			</div>
			<div class="actions">
				<%= f.submit %>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<%= form_for([@comedian, @review]) do |f| %>
	<div class="field">
		<%= f.label :rating %><br>
		<%= f.number_field :rating %>
	</div>	
	<div class="field">
		<%= f.label :comment %><br>
		<%= f.text_field :comment %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/reviews/new.html.erb
<% if @return_type == 'show' %>
  <%= render 'shows/show_form' %>
<% else %>
  <%= render 'reviews/comedian_form' %>
<% end %>